version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules/
    working_dir: /app
    ports:
      - 42500:3000
volumes:
  app_node_modules:
    driver: local
